services:
  fcrepo:
    image: fcrepo/fcrepo:latest
    ports:
      - "8080:8080"
    environment:
      CATALINA_OPTS: "-Dfcrepo.jms.baseUrl=http://fcrepo:8080 -Dfcrepo.metrics.enable=true"

  solr:
    image: solr:8
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - fcrepo

  fuseki:
    image: atomgraph/fuseki
    ports:
      - "3030:3030"
    command:
      - --mem
      - /fcrepo

  camel-toolbox:
    image: fcrepo/fcrepo-camel-toolbox:latest
    volumes:
      - "./camel-toolbox-config:/config"
    ports:
      - "9080:9080"
    command:
      - -c
      - "/config/configuration.properties"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
    - "3000:3000"
