scrape_configs:
  - job_name: 'fcrepo'
    scrape_interval: 30s
    metrics_path: '/fcrepo/prometheus'
    static_configs:
    - targets: ['fcrepo:8080']
    basic_auth:
      username: fedoraAdmin
      password: fedoraAdmin
